{
 "title": "Trace Differencing",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Customer Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_customer_http_requests_total[1m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Success by Endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\".*_requests_total\",status_code=\"2xx\"}[30s])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Latency Histogram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Number of Requests" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_customer_request_latency_bucket{error=\"false\",le=~\"0.1|1.0\"}[1m])",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Total requests by Status Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".*_requests_total\"}[30s])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\".*_request_latency_sum\",endpoint!~\".*/metrics\",error=\"false\"}[30s])"
    }
   ]
  }
 ]
}